config/routes.rb
Rails.application.routes.draw do

  root "homepage#index"

  resources :recipes

  resources :reviews

  get 'recent', to: 'recipes#recent'
  get 'categories', to: 'recipes#categories'
  get 'imprint', to: 'homepage#imprint'
  get 'privacy', to: 'homepage#privacy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  UNITS = %w(g ml EL TL)

  belongs_to :recipe
end

app/models/recipe.rb
require 'open-uri'

class Recipe < ApplicationRecord
  has_one_attached :uploaded_image
  has_many :ingredients, inverse_of: :recipe, dependent: :destroy
  has_many :reviews, inverse_of: :recipe, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank

  validates_presence_of :title, :description, :author
  validate :presence_of_image

  def image
    return if new_record?
    return image_url if image_url.present?
    Rails.application.routes.url_helpers.rails_blob_path(uploaded_image, only_path: true)
  end

  protected

  def working_url?
    uri = URI.parse(image_url)
    return false unless uri.is_a?(URI::HTTP) && !uri.host.nil?

    req = Net::HTTP.new(uri.host, uri.port)
    req.use_ssl = true
    res = req.request_head(uri.path)
    res.code == '200'
  rescue URI::InvalidURIError, SocketError
    false
  end

  def presence_of_image
    return errors.add(:image_url, 'muss ausgefüllt werden') unless image_url.present? || uploaded_image.attached?

    attached_image? if uploaded_image.attached?
    return if uploaded_image.attached? && image_url.blank?
    return errors.add(:image_url, 'must have an image extension') unless image_url.match(/\.(gif|jpe?g|png|webp)$/)
    return if working_url?

    errors.add(:image_url, 'URL ist nicht erreichbar')
  end

  def attached_image?
    return errors.add(:image_url, 'muss ausgefüllt werden') unless uploaded_image.attached?
    return if uploaded_image.content_type.in?(%w(image/jpeg image/png image/webp image/gif))

    errors.add(:image_url, 'darf nur diese formate haben jpeg, png, webp, gif')
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :recipe, foreign_key: :recipe_id

  scope :by_recipe, -> (recipe_id) { where(recipe_id: recipe_id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @recipes = Recipe.with_attached_uploaded_image.order(created_at: :desc)
  end

  def imprint
    head :ok
  end

  def privacy
    head :ok
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  def recent
    head :ok
  end

  def categories
    head :ok
  end

  def show; end

  def new
    @recipe = Recipe.new
  end

  def edit; end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: "Recipe was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: "Recipe was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_url, notice: "Recipe was successfully destroyed."
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :author, :description, :image_url, :uploaded_image,
                                   ingredients_attributes: [:id, :name, :amount, :unit, :_destroy])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  protect_from_forgery with: :exception

  def create
    @review = Review.create!(review_params)
    render json: average_rating
  end

  private

  def review_params
    params.require(:review).permit(:recipe_id, :rating)
  end

  def average_rating
    reviews = Review.by_recipe(params[:recipe_id])
    if reviews.size > 1
      reviews.average(:rating)&.round(2)
    else
      reviews.first.rating
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
      id = new_object.object_id
      fields = f.fields_for(association, new_object, child_index: id) do |builder|
        render(association.to_s.singularize + "_fields", f: builder)
      end

      link_to(name, '#', class: "add_fields btn btn-primary btn-sm", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/homepage/index.html.erb
<section class="text-center container">
  <div class="row">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h2 class="fw-light">Willkommen zum Rezeptbuch</h2>
      <%= link_to "Neues Rezept erstellen", new_recipe_path, class: "btn btn-sm btn-primary" %>
    </div>
  </div>
</section>
<div class="album py-4">
  <div class="container-lg">
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-3">
      <% @recipes.each do |recipe| %>
        <div class="col">
          <div class="card shadow-sm">
            <%= link_to recipe_path(recipe) do |variable| %>
              <%= image_tag recipe.image, class: 'img-fluid', alt: recipe.title, width: "640", height: "360" %>
            <% end %>
            <div class="card-body">
              <h3 class="card-text text-center mb-3"><%= recipe.title %></h3>
              <div class="d-flex justify-content-center">
                <div class="btn-group">
                  <%= link_to "Ansehen", recipe_path(recipe) , class: 'btn btn-sm btn-outline-secondary' %>
                  <%= link_to "Bearbeiten", edit_recipe_path(recipe) , class: 'btn btn-sm btn-outline-secondary' %>
                  <%= link_to "Löschen", recipe, method: :delete, data: {confirm: "Bist du sicher?"}, class: 'btn btn-sm btn-outline-danger' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title).presence || "Rezeptbuch" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <header>
      <div class="navbar navbar-expand-sm navbar-dark bg-dark shadow-sm">
        <div class="container-fluid">
          <%= link_to root_path, class: 'navbar-brand' do %>
            <h1 class="mb-0">Rezeptbuch</h1>
          <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <%= link_to "Aktuelles", recent_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Kategorien", categories_path, class: 'nav-link' %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>
    <main class="container-lg pt-3 flex-grow-1">
      <%= yield %>
    </main>
    <footer class="footer py-3 border-top mt-3">
      <ul class="nav d-flex justify-content-center">
        <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link px-2 text-muted"%></li>
        <li class="nav-item"><%= link_to "Aktuelles", recent_path, class: "nav-link px-2 text-muted"%></li>
        <li class="nav-item"><%= link_to "Kategorien", categories_path, class: "nav-link px-2 text-muted"%></li>
        <li class="nav-item"><%= link_to "Impressum", imprint_path, class: "nav-link px-2 text-muted"%></li>
        <li class="nav-item"><%= link_to "Datenschutz", privacy_path, class: "nav-link px-2 text-muted"%></li>
      </ul>
    </footer>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with model: recipe, local: true do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :title, class: 'form-label' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :author, class: 'form-label' %>
    <%= f.text_field :author, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :description, class: 'form-label' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label "Bild auswählen", class: 'form-label' %>
    <div class="input-group">
      <%= f.file_field :uploaded_image, class: 'form-control' %>
    </div>
    <div>oder Bild-URL angeben</div>
    <%= f.text_field :image_url, class: 'form-control', placeholder: 'Bild URL' %>
  </div>


  <div class="mb-3">
    <h3>Zutaten</h3>
    <%= f.fields_for :ingredients do |ri| %>
      <%= render "ingredient_fields", f: ri %>
    <% end %>
    <%= link_to_add_fields "Zutaten hinzufügen", f, :ingredients %>
  </div>

  <div class="d-flex justify-content-between">
    <div class="btn-group">
      <%= link_to 'Zurück', :back, class: 'btn btn-outline-secondary' %>
      <%= link_to "Ansehen", recipe_path(recipe) , class: 'btn btn-outline-secondary' unless recipe.new_record? %>
    </div>
    <%= f.submit "Speichern", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
  <%= f.hidden_field :_destroy %>
  <div class="input-group mb-3">
    <%= f.text_field :name, class: 'form-control', placeholder: 'Ingwer' %>
    <%= f.number_field :amount, class: 'form-control', placeholder: '100', step: :any %>
    <%= f.select :unit, Ingredient::UNITS, {:include_blank => "Maßeinheit auswählen"}, {:class => "form-select"} %>
  </div>
  <%= link_to "Löschen", '#', class: "remove_fields btn btn-danger btn-sm mb-3 float-end" %>
</div>

app/views/recipes/edit.html.erb
<div class="d-flex justify-content-between">
  <h2>Rezept bearbeiten</h2>
  <%= link_to "Löschen", @recipe, method: :delete, data: {confirm: "Bist du sicher?"}, class: 'btn btn-outline-danger' %>
</div>

<%= render 'form', recipe: @recipe %>

app/views/recipes/new.html.erb
<h2>Neues Rezept</h2>

<%= render 'form', recipe: @recipe %>

app/views/recipes/show.html.erb
<div class="row justify-content-center">
  <div class="col-md-11">
    <%= image_tag @recipe.image, class: 'img-fluid shadow' %>
  </div>
</div>

<div class="row justify-content-center mx-0 mt-md-n5">
  <div class="col-md-10 card p-md-4">
    <div class="card-body py-3 px-2">
      <h2 class="card-title">
        <%= @recipe.title %>
      </h2>
      <h3 class="card-subtitlet text-muted mb-2 row justify-content-between">
        <div class="col">
          <%= @recipe.author %>
        </div>
        <div class="col text-sm-end">
          <%= @recipe.created_at.to_s(:long) %>
        </div>
      </h3>
      <p class="card-text mb-2">
        <%= @recipe.description %>
        <% if @recipe.ingredients.any? %>
          <h4>Zutaten</h4>
          <ul>
            <% @recipe.ingredients.each do |ingredient| %>
              <li><%= "#{ingredient.name} #{number_to_human(ingredient.amount)} #{ingredient.unit}" %></li>
            <% end %>
          </ul>
        <% end %>
      </p>
      <div class="d-flex flex-wrap">
        <div class="stars me-2">
          <i class="bi bi-star"></i>
          <i class="bi bi-star"></i>
          <i class="bi bi-star"></i>
          <i class="bi bi-star"></i>
          <i class="bi bi-star"></i>
        </div>
        <span id="review_result" class="me-2" data-recipe-id="<%= @recipe.id %>" data-review="1">
          <%= @recipe.reviews.average(:rating)&.round(2) %>
        </span>
        <span id="review_count" data-review-count="<%= @recipe.reviews.size %>">
          <%= "(#{@recipe.reviews.size} Bewertungen)" %>
        </span>
      </div>
      <div class="container p-0 m-0">
        <div id="post_review" class="mt-2 btn btn-sm btn-primary disabled">Bewertung Absenden</div>
      </div>
      <div class="btn-group mt-3">
        <%= link_to 'Zurück', :back, class: 'btn btn-outline-secondary' %>
        <%= link_to "Bearbeiten", edit_recipe_path(@recipe) , class: 'btn btn-outline-secondary' %>
      </div>
    </div>
  </div>
</div>